// These run in Xcode (⌘U) or `swift test` on the Mac. The fixture is a real
// snapshot from the shipped desk, regenerated by tests/test_apple.py on the
// Python side so the two never drift.
import XCTest
@testable import DeskKit

final class SnapshotDecodingTests: XCTestCase {
    func fixture() throws -> Data {
        let url = try XCTUnwrap(Bundle.module.url(forResource: "snapshot", withExtension: "json", subdirectory: "Fixtures"))
        return try Data(contentsOf: url)
    }

    func testDecodesTheShippedSnapshot() throws {
        let snap = try DeskJSON.decoder().decode(Snapshot.self, from: fixture())
        XCTAssertEqual(snap.mode.execution, "research_packs_only")
        XCTAssertTrue(snap.mode.liveVenues.isEmpty, "no venue is live")
        XCTAssertFalse(snap.stamp.stamps.isEmpty)
        for s in snap.stamp.stamps { XCTAssertEqual(s.stampSha256.count, 64) }
    }

    func testNothingIsConfirmableOnTheShippedBook() throws {
        let snap = try DeskJSON.decoder().decode(Snapshot.self, from: fixture())
        XCTAssertTrue(snap.stamp.stamps.allSatisfy { !$0.confirmable })
    }

    func testANaiveTimestampFailsToDecode() {
        let bad = #"{"ok": true, "when": "2026-09-22T06:30:00"}"#.data(using: .utf8)!
        struct T: Codable { var ok: Bool; var when: Date }
        XCTAssertThrowsError(try DeskJSON.decoder().decode(T.self, from: bad))
    }
}

final class AgeTests: XCTestCase {
    let now = Date(timeIntervalSince1970: 1_790_000_000)
    func testBands() {
        XCTAssertEqual(Age(now.addingTimeInterval(-600), now: now).freshness, .fresh)
        XCTAssertEqual(Age(now.addingTimeInterval(-2 * 3600), now: now).freshness, .aging)
        XCTAssertEqual(Age(now.addingTimeInterval(-7 * 3600), now: now).freshness, .stale)
        XCTAssertEqual(Age(nil, now: now).freshness, .missing)
        XCTAssertEqual(Age(nil, now: now).label, "none yet")
    }
}

final class PairingTests: XCTestCase {
    func testParsesTheOneTimeURL() throws {
        let p = try XCTUnwrap(Pairing.parse("http://100.64.0.2:8791/?token=abc123"))
        XCTAssertEqual(p.baseURL.absoluteString, "http://100.64.0.2:8791")
        XCTAssertEqual(p.token, "abc123")
    }
    func testRefusesAURLWithoutAToken() {
        XCTAssertNil(Pairing.parse("http://127.0.0.1:8791/"))
        XCTAssertNil(Pairing.parse("not a url"))
    }
}

final class ConfirmRequestTests: XCTestCase {
    func testEncodesTheServerFieldNames() throws {
        let data = try JSONEncoder().encode(ConfirmRequest(ticketId: "T", stampSha256: "d", device: "iphone"))
        let obj = try XCTUnwrap(JSONSerialization.jsonObject(with: data) as? [String: Any])
        XCTAssertEqual(obj["ticket_id"] as? String, "T")
        XCTAssertEqual(obj["stamp_sha256"] as? String, "d")
        XCTAssertEqual(obj["device"] as? String, "iphone")
    }
}
